# Generated by Django 4.2.1 on 2023-05-10 00:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Indicators',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_owner', models.CharField(max_length=60)),
                ('gas', models.CharField(max_length=60)),
                ('water', models.CharField(max_length=100)),
                ('electric', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NotOwners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('mail', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('home_adress', models.CharField(blank=True, default='empty', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Owners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=60)),
                ('mail', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=60)),
                ('land_adress', models.CharField(blank=True, default='empty', max_length=100, null=True)),
                ('home_adress', models.CharField(blank=True, default='empty', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_ads', models.CharField(choices=[('IM', 'Important'), ('OR', 'Ordinary')], default='OR', max_length=2)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
