# Generated by Django 4.2.1 on 2023-05-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='type_ads',
            field=models.CharField(choices=[('Important', 'Important'), ('Ordinary', 'Ordinary')], default='Ordinary', max_length=9),
        ),
    ]
